# fly.toml app configuration file generated for go-momentum-api-cold-dawn-7307 on 2025-06-28T14:08:47+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'go-momentum-api-cold-dawn-7307'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[checks]
  [checks.alive]
    type = "http"
    port = 8080
    path = "/api/health"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"